<?php

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use \Drupal\node\NodeInterface;

/**
 * Implements hook_entity_view_alter().
 */
function comment_rest_jquery_entity_view_alter(&$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $build['#cache']['contexts'][] = 'user.roles:authenticated';
  if ($entity instanceof NodeInterface && \Drupal::currentUser()->isAuthenticated()) {
    $build['#attached']['library'][] = 'comment_rest_jquery/demo';
  }
}
