<?php

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;

/**
 * Implements hook_form_ID_alter() for the form with ID 'comment_comment_form'.
 */
function comment_ajax_form_comment_comment_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'comment_ajax/preview';

  $form['actions']['preview']['#ajax'] = [
    // @see \Drupal\comment\CommentForm::ajaxPreview()
    'callback' => '::ajaxPreview',
  ];
  $form['#prefix'] = '<div id="comment-ajax-preview-placeholder"></div>';
}
